-- MySQL Script generated by MySQL Workbench
-- Fri Jun 30 22:36:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema viviendas_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema viviendas_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `viviendas_2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `viviendas_2` ;

-- -----------------------------------------------------
-- Table `viviendas_2`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`provincia` (
  `cod_provincia` VARCHAR(5) NOT NULL,
  `nombre_provincia` VARCHAR(22) NOT NULL,
  `tasa_desempleo` FLOAT NULL,
  `empleo_no_remunerado` FLOAT NULL,
  `empleo_bruto` FLOAT NULL,
  `asistencia_edu_basica` FLOAT NULL,
  `tasa_analfabetismo` FLOAT NULL,
  PRIMARY KEY (`cod_provincia`),
  UNIQUE INDEX `cod_provincia_UNIQUE` (`cod_provincia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`canton` (
  `cod_canton` VARCHAR(22) NOT NULL,
  `nombre_canton` VARCHAR(100) NOT NULL,
  `provincia_canton` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`cod_canton`),
  INDEX `provincia_canton` (`provincia_canton` ASC) VISIBLE,
  UNIQUE INDEX `cod_canton_UNIQUE` (`cod_canton` ASC) VISIBLE,
  CONSTRAINT `canton_ibfk_1`
    FOREIGN KEY (`provincia_canton`)
    REFERENCES `viviendas_2`.`provincia` (`cod_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`parroquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`parroquia` (
  `cod_parroquia` VARCHAR(55) NOT NULL,
  `nombre_canton` VARCHAR(55) NOT NULL,
  `cod_canton` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`cod_parroquia`),
  INDEX `cod_canton` (`cod_canton` ASC) VISIBLE,
  UNIQUE INDEX `cod_parroquia_UNIQUE` (`cod_parroquia` ASC) VISIBLE,
  CONSTRAINT `ciudad_ibfk_1`
    FOREIGN KEY (`cod_canton`)
    REFERENCES `viviendas_2`.`canton` (`cod_canton`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`vivienda` (
  `id_vivienda` VARCHAR(22) NOT NULL,
  `tipo_vivienda` VARCHAR(35) NOT NULL,
  `nro_vivienda` INT NOT NULL,
  `estrato` VARCHAR(20) NOT NULL,
  `area` VARCHAR(10) NOT NULL,
  `conglomerado` VARCHAR(10) NOT NULL,
  `cod_parroquia` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`id_vivienda`),
  INDEX `cod_ciudad` (`cod_parroquia` ASC) VISIBLE,
  UNIQUE INDEX `id_vivienda_UNIQUE` (`id_vivienda` ASC) VISIBLE,
  CONSTRAINT `vivienda_ibfk_1`
    FOREIGN KEY (`cod_parroquia`)
    REFERENCES `viviendas_2`.`parroquia` (`cod_parroquia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`hogar` (
  `id_hogar` VARCHAR(22) NOT NULL,
  `id_vivienda` VARCHAR(22) NOT NULL,
  `nro_hogar` INT NOT NULL,
  `tipo_tenencia` VARCHAR(35) NOT NULL,
  `acceso_principal` VARCHAR(35) NOT NULL,
  `cant_vehiculos` INT NOT NULL,
  `cant_motos` INT NOT NULL,
  `ducha` VARCHAR(35) NOT NULL,
  `combustible_cocina` VARCHAR(20) NOT NULL,
  `material_techo` VARCHAR(45) NOT NULL,
  `estado_techo` VARCHAR(15) NOT NULL,
  `material_piso` VARCHAR(55) NOT NULL,
  `estado_piso` VARCHAR(15) NOT NULL,
  `material_paredes` VARCHAR(45) NOT NULL,
  `estado_paredes` VARCHAR(15) NOT NULL,
  `valor_arriendo` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `fexp` VARCHAR(20) NOT NULL,
  `upm` VARCHAR(16) NOT NULL,
  `periodo` VARCHAR(10) NOT NULL,
  `mes` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_hogar`),
  INDEX `id_vivienda` (`id_vivienda` ASC) VISIBLE,
  UNIQUE INDEX `id_hogar_UNIQUE` (`id_hogar` ASC) VISIBLE,
  CONSTRAINT `hogar_ibfk_1`
    FOREIGN KEY (`id_vivienda`)
    REFERENCES `viviendas_2`.`vivienda` (`id_vivienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`cuartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`cuartos` (
  `nro_cuartos` INT NOT NULL,
  `nro_dormitorios` INT NOT NULL,
  `nro_cuartos_negocio` INT NOT NULL,
  `cuarto_cocina` VARCHAR(5) NOT NULL,
  `id_hogar` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id_hogar`),
  UNIQUE INDEX `id_hogar_UNIQUE` (`id_hogar` ASC) VISIBLE,
  CONSTRAINT `fk_cuartos_hogar1`
    FOREIGN KEY (`id_hogar`)
    REFERENCES `viviendas_2`.`hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`datos_arriendo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`datos_arriendo` (
  `agua_incluida` VARCHAR(5) NULL DEFAULT NULL,
  `luz_incluida` VARCHAR(5) NULL DEFAULT NULL,
  `parentesco_propietario` VARCHAR(5) NULL DEFAULT NULL,
  `id_hogar` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id_hogar`),
  UNIQUE INDEX `id_hogar_UNIQUE` (`id_hogar` ASC) VISIBLE,
  CONSTRAINT `fk_datos_arriendo_hogar1`
    FOREIGN KEY (`id_hogar`)
    REFERENCES `viviendas_2`.`hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`hogar_combustibles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`hogar_combustibles` (
  `id_hogar` VARCHAR(22) NOT NULL,
  `tipo_combustible` VARCHAR(22) NOT NULL,
  `gasto_combustible` INT NOT NULL,
  PRIMARY KEY (`id_hogar`),
  CONSTRAINT `hogar_combustibles_ibfk_1`
    FOREIGN KEY (`id_hogar`)
    REFERENCES `viviendas_2`.`hogar` (`id_hogar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `viviendas_2`.`servicios_basicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `viviendas_2`.`servicios_basicos` (
  `servicio_higienico` VARCHAR(30) NOT NULL,
  `SSHH_alternativa` VARCHAR(65) NULL DEFAULT NULL,
  `SSHH_prestado` VARCHAR(30) NULL DEFAULT NULL,
  `agua_obtencion` VARCHAR(30) NOT NULL,
  `tipo_alumbrado` VARCHAR(30) NOT NULL,
  `agua_medidor` VARCHAR(5) NOT NULL,
  `agua_junta` VARCHAR(5) NOT NULL,
  `agua_tuberia` VARCHAR(55) NOT NULL,
  `eliminacion_basura` VARCHAR(35) NOT NULL,
  `id_hogar` VARCHAR(22) NOT NULL,
  PRIMARY KEY (`id_hogar`),
  UNIQUE INDEX `hogar_id_hogar_UNIQUE` (`id_hogar` ASC) VISIBLE,
  CONSTRAINT `fk_servicios_basicos_hogar1`
    FOREIGN KEY (`id_hogar`)
    REFERENCES `viviendas_2`.`hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
